### ISSUE TITLE
Command to Guess Next GitHub Repo Issue Number

### ISSUE THREAD

**Issue by raamdev** [websharks/ws-commander#2]
@jaswsinc While I was watching your [recent Typinator video](http://youtu.be/f5KihOtekyc), I realized that the one thing we haven't yet automated is the insertion of the GitHub Issue URL into the `github-issue:` YAML config. 

The reason for this is because we have no way of getting the GitHub Issue number until we've actually created the GitHub Issue. However, we could _guess_ the next GitHub Issue number, if we know what the last Issue number was...

Typinator has a scripting feature that we could utilize for this...

```
[...]
github-issue: {Scripts/s2member-kb-GitHub-Issue-URL.applescript}
[...]
```

The `s2member-kb-GitHub-Issue-URL.applescript` script would call upon, perhaps, the WS Commander and run something like `ws github s2member-kb next-issue-url`, which would simply return something like `http://github.com/websharks/s2member-kb/issues/72`, which Typinator would add to the `github-issue:` YAML key whenever you run the Typinator macro...

The WS Commander could utilize the [Node GitHub Library](https://github.com/mikedeboer/node-github) to interface with the GitHub API to retrieve a list of Issue for a given Repo, sorted newest to oldest, find the newest Issue and add 1 to that Issue number to "guess" the next Issue number and return that in a URL form.

This would save us from creating the GitHub Issue, copying the GitHub Issue URL, editing the GitHub Issue, pasting in the URL, and then finally saving the GitHub Issue again. Instead, after creating our new KB GitHub Issue, we'd just need to verify that the new Issue URL and the Issue URL that Typinator added both match--a quick visual check. If they're wrong (e.g., if someone else created a new Issue between the time we generated ours and when we created our GitHub Issue--the numbers would be off by one in that case), then we simply do what we do now and correct the URL.
#### Gotchas

This would require a separate Typinator macro for each KB GitHub Repo (one for `s2member-kb`, one for `zencache-kb`, etc.), because we'd need to call upon a slightly different script each time, passing in the necessary repo name. I'm personally fine with separate Typinator macros for each repo, but if that made this solution to guessing and getting the GitHub Issue URL more inconvenient for you guys, then this wouldn't be worth doing.

---

@jaswsinc What do you think? Worth doing?

**Comment by brucewrks** [comment]
The `ws-install` script already prompts for a GitHub API Personal Access Token. This would only require accessing one endpoint on the GitHub API.

See: https://developer.github.com/v3/issues/#list-issues-for-a-repository

**Comment by jaswrks** [comment]
> What do you think? Worth doing?

Love it! That would be a great learning experience too. I really have been meaning to play around with the new JavaScript API. If it's written in AppleScript that would cool also.

I was just thinking that if this was written as a Chrome extension we'd have access to the current URL. So if were you writing the KB article from GitHub in Chrome, we could detect the current URL, and thus the current repo. Maybe that's possible in the the AppleScript too.

> See: https://developer.github.com/v3/issues/#list-issues-for-a-repository

Cool. I can see myself using this. Definitely!

**Comment by raamdev** [comment]
> I was just thinking that if this was written as a Chrome extension we'd have access to the current URL. So if were you writing the KB article from GitHub in Chrome, we could detect the current URL, and thus the current repo. Maybe that's possible in the the AppleScript too.

Right, but I don't see that helping us in the scenario I described: If we're writing the KB article in Chrome, the current URL will still be `/issues/new` when composing a new KB Article, i.e., we don't have access to the Issue Number.

And as far as getting the GitHub Repo via the URL in Chrome: Yes, but that doesn't help us in the Typinator macro, which needs to be pre-configured to call upon a script (an AppleScript, I believe). There would be no way of passing Chrome's knowledge the current repo you're working on to Typinator. If there was some way of setting an environment variable from a Chrome extension--not possible, I think--but if it were possible, we could dynamically set something like `$CURRENT_BROWING_GITHUB_REPO` and have the `ws` utility read that when querying the GitHub API... 

(Or maybe you were thinking we could use a Chrome extension to query the GitHub API... in that case, yeah, we could make use of the current URL we're browsing to extract the repo...)

**Comment by jaswrks** [comment]
> (Or maybe you were thinking we could use a Chrome extension to query the GitHub API... in that case, yeah, we could make use of the current URL we're browsing to extract the repo...)

Yes, that's what I had in mind. The Chrome extension could collect the current URL: `http://github.com/repo/owner/` and then query the GitHub API using JavaScript which would read the reponse as JSON and determine the next issue number. That does limit this to Google Chrome though, so if you prefer to edit Markdown files in Emacs, Atom, or something like Mou; that could be limiting.

> And as far as getting the GitHub Repo via the URL in Chrome: Yes, but that doesn't help us in the Typinator macro, which needs to be pre-configured to call upon a script (an AppleScript, I believe). There would be no way of passing Chrome's knowledge the current repo you're working on to Typinator.

I think maybe we _can_ do this with Typinator. I've not written one of these before though, so maybe you're right. In looking over the Script Editor and at the Chrome properties/methods exposed, it seems doable.

![2015-01-23_16-27-35](https://cloud.githubusercontent.com/assets/1563559/5885583/4afd5a0c-a31d-11e4-8ab9-cb7cf32eea8e.png)

**Comment by raamdev** [comment]
> I think maybe we can do this with Typinator. I've not written one of these before though, so maybe you're right. In looking over the Script Editor and at the Chrome properties/methods exposed, it seems doable.

Oh! Great idea! I had not even thought about using AppleScript to get the URL of the current tab in Chrome, but you're absolutely right. As of Chrome 7+, there is support for AppleScript, so this works!

``` applescript
tell application "Google Chrome"
    get URL of active tab of first window
end tell
```

So, if we had a command line utility that we could pass that URL (something like `ws github next-issue-url [Current Chrome Tab URL]`), that utility could query the GitHub API and return something like `http://github.com/websharks/s2member-kb/issues/72`.

**Comment by jaswrks** [comment]
> get URL of active tab of first window

Cool! Thanks for that example.

> So, if we had a command line utility that we could pass that URL (something like ws github next-issue-url [Current Chrome Tab URL]), that utility could query the GitHub API and return something like http://github.com/websharks/s2member-kb/issues/72.

Yep, that sounds like it could work. @brucewsinc There's your mission on that one :-)

`ws github next-issue-url [GitHub URL]`

```
var url = 'https://github.com/websharks/test-repo/issues/new',
    regex = /^https?\:\/\/github\.com\/([^\/]+)\/([^\/]+)/i,
    matches, github = {owner:'', repo: ''};

if(matches = url.match(regex))
    github.owner = matches[1], github.repo = matches[2];

console.log(github); // {owner: "websharks", repo: "test-repo"}
```

Fiddle: http://jsfiddle.net/JasWSInc/hw3qq3zx/

**Comment by brucewrks** [comment]
No problem! I'll work on having this added in tomorrow + I'll be releasing documentation in a Gist or Issue here on how we can use the WS Commander.

**Comment by brucewrks** [comment]
This has been added and is ready to merge in #3

**Comment by brucewrks** [comment]
@jaswsinc This command is ready. You can do whatever you need to on the Chrome extension / Typinator Macro now.

**Comment by raamdev** [comment]
@brucewsinc Woohoo! Thanks for adding this in! I'm now working on an AppleScript that uses this so we can make use of this functionality inside Typinator macros. :dancers:

**Comment by jaswrks** [comment]
Wow! :trophy: Works great. Thank you so much, both of you.
I'm heading over to check out the Typinator video next.

![2015-01-24_18-13-33](https://cloud.githubusercontent.com/assets/1563559/5890074/fba3be14-a3f4-11e4-9605-3a70ec26a4d3.png)

**Comment by jaswrks** [comment]
@brucewsinc Quick observation...

The KB repos generally contain longer issues with a lot of text in them. Whenever you query the GitHub API it returns 30 issues with all of that text; adding to the latency associated with this command.

I suggest that you add the `per_page=1` query parameter. Given the tuning that you've already done, adding that additional parameter should require that you only pull the latest `1` issue to determine the next issue number. That could shave several bytes off the request body and reduce latency here.

![2015-01-25_04-03-57](https://cloud.githubusercontent.com/assets/1563559/5891519/3e3ff880-a447-11e4-9b82-fbc1c1b98fd8.png)

**Comment by brucewrks** [comment]
Great idea. I'll add that in now.

**Comment by brucewrks** [comment]
This was added. You need to `git pull` and reinstall with `npm install -g ws-commander`

**Comment by jaswrks** [comment]
Great. Thanks!
